---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-api-deployment
  namespace: pets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pets-api
  template:
    metadata:
      labels:
        app: pets-api
    spec:
      containers:
        - name: pets-api
          image: pets/api:2
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
