---
apiVersion: v1
kind: Pod
metadata:
  name: pets-api
  namespace: pets
  labels:
    app: pets-api
spec:
  containers:
    - name: pets-api
      image: pets/api:2
      ports:
        - containerPort: 8080
      imagePullPolicy: Never