---
apiVersion: v1
kind: Service
metadata:
  name: pets-api-service
  namespace: pets
spec:
  selector:
    app: pets-api
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30007
  type: NodePort